feat: streamline sandbox ops & custom ver
near/near-sandbox pull request #72
Opened 2023-10-26 15:46 UTC by shariffdev

wip: TBA

2023-11-01 14:54 UTC, shariffdev commented
@ChaoticTempest @frol Ready for review

2023-11-28 22:39 UTC, frol requested changes

2023-11-28 22:39 UTC, frol commented on crate/src/lib.rs
> +}
1. Let's not make it `pub` as I don't think it is worth maintaining API compatibility in the future.
2. There is no reason to have `AsRef<str>` as all the calls for this function have `&str` as input
3. There is no need for Regex for a simple replacement (don't forget to remove it from the dependencies)

```suggestion
fn normalize_name(input: &str) -> String {
    input.as_ref().replace('/', "_")
}
```

2023-11-28 22:39 UTC, frol commented on crate/src/lib.rs
> +pub fn bin_path(version: &str) -> anyhow::Result<PathBuf> {
Now we have a breaking change since public function has different signature. I am strongly considering to un-pub this method as I don't see a reason anyone would need to use it

2024-07-05 13:10 UTC, frol approved these changes

2024-07-05 13:12 UTC, merged